### ISSUE TITLE
Item Frame Visibility

### ISSUE THREAD

**Issue by beouwolfe** [FlorentTomi/ArmorStatuesCompanion#11]
When in the key bind menu (my period is used for something else), I see an option to key bind the item frame visibility. But I didn't see this option in the main gui.

**Comment by FlorentTomi** [comment]
This was done by design. I tried to keep only the armor stand content in the GUI.
This key bind has been added to avoid having to type the command again and again (punching an item frame happens so often!) and having to enter a specific GUI for this case felt overkill.
