### ISSUE TITLE
Description Suggestion

### ISSUE THREAD

**Issue by beouwolfe** [FlorentTomi/ArmorStatuesCompanion#12]
It would help if the description would say what the default key is and that the key bind can be changed. Also including a screenshot of what the gui looks like in game would be a benefit. I have skipped over mods before because they did not give me any indication of how they worked or how it looked in game.

**Comment by FlorentTomi** [comment]
Added in 1.3.0+1.20.1 (coming soon™)

**Comment by FlorentTomi** [comment]
Fixed!
