### ISSUE TITLE
Statues Book Update

### ISSUE THREAD

**Issue by beouwolfe** [FlorentTomi/ArmorStatuesCompanion#13]
The latest version of the statues book (the file lists the version as 2.9.4, in game the book says 2.10) has removed the Name feature under Style and replaced it with Has Visual Fire. There are also options to create wands in the book. Although, I can understand about skipping including those options.

**Comment by FlorentTomi** [comment]
The removal of the name feature is flagged as a bug in the statues book repo (https://github.com/MukiTanuki/armor-statues/issues/17). I guess wait-and-see for now?

For the wand feature, it will be added in the next feature version.

**Comment by FlorentTomi** [comment]
Will be "fixed" in 1.3.0+1.20.1.
I'll disable the "name" feature in the time being, and add the "visual fire"

**Comment by FlorentTomi** [comment]
Fixed!

**Comment by MukiTanuki** [comment]
Not a bug, the way you name armor stand is automatic in the newest version.  see the changelog: https://legacy.curseforge.com/minecraft/customization/armor-statues-datapack/files/4469497
You can rename an armor stand item in an anvil and place it down in order for it to display its name.
