### ISSUE TITLE
1.20.4 fixes

### ISSUE THREAD

**Issue by ghost** [FlorentTomi/ArmorStatuesCompanion#17]
1.20.2 / 1.4.0 launches on 1.20.4 and some of it's features function.
other buttons cause a crash when pressed.

crash report:
https://pastebin.com/xz46GsLk

**Comment by FlorentTomi** [comment]
Hello,
v1.4.0 wasn't compatible with 1.20.4 (owo-lib wasn't updated yet at this point in time).
The new version v1.4.1 has been pushed with 1.20.4 support.
Enjoy!
