### ISSUE TITLE
GUI Obstructed in Different GUI Scales

### ISSUE THREAD

**Issue by rmcdaniel76** [FlorentTomi/ArmorStatuesCompanion#8]
GUI Obstructed in GUI 3
<img width="245" alt="Screenshot 2023-06-26 175301" src="https://github.com/FlorentTomi/ArmorStatuesCompanion/assets/126378894/c4c56190-570c-41a8-87e4-e6e3a1041e5e">

**Comment by FlorentTomi** [comment]
Hello,

I submitted an issue in the GUI library I used (owo-lib): https://github.com/wisp-forest/owo-lib/issues/140
If nothing is done on their side, I'll probably switch to another GUI library in the next version.

Thank you for taking time to post the issue :)

**Comment by FlorentTomi** [comment]
The issues has been "fixed" with the version 1.2.1+1.20.1.
